version: 2

jobs:
  - docker:
      image: golang:1.18-buster
    template:
      name: go
      skip:
        - test  # CI tests require a database

branches:
  - name: main
  - name: 2.x
  - name: v1

publications:
  - url: https://pkg.go.dev/github.com/launchdarkly/go-server-sdk-dynamodb/v3
    description: documentation
